### ISSUE TITLE
Example code error

### ISSUE THREAD

**Issue by Valentina2311** [Litterman/EZClimate#4]
I tried to run the example code from the documentation on Python 3.7 (https://oscarsjogren.github.io/dlw/examples/output_paper.html) and I encountered two errors: 

`df.damage_simulation(draws=4000000, peak_temp=6.0, disaster_tail=18.0, tip_on=True, 
						 temp_map=1, temp_dist_params=None, maxh=100.0)`

`File "C:\Users\admin\Anaconda3\lib\site-packages\ezclimate\tools.py", line 48, in write_columns_csv
    writer.writerow(row)`
`TypeError: a bytes-like object is required, not 'str'`

![console1](https://user-images.githubusercontent.com/48785057/54737436-2d988700-4b6d-11e9-9935-1fa6dd00d6a5.JPG)
and then

`final_pop, fitness = ga_model.run()`

` File "C:\Users\admin\Anaconda3\lib\multiprocessing\pool.py", line 683, in get
    raise self._value`

`IndexError: too many indices for array`

Do you have any idea what the issue might be? Any help with running the code is greatly appreciated!

![console2](https://user-images.githubusercontent.com/48785057/54737457-4ef97300-4b6d-11e9-9f8b-03e3d9cf95fe.JPG)

**Comment by gwagnerGH** [comment]
Thanks for the ping. I discovered a couple of these (and more) errors myself these past couple of days of re-running the code. Update to come today or tomorrow.

**Comment by gwagnerGH** [comment]
A bit more for now:

The latest code runs fine for me, though I've created a new "main" file from scratch, calling up the rest. Please email me for the file. Would be great if you could test that it does indeed work.

We'll update documentation here once our own (re)runs are complete, which may take another 2-3 weeks.

**Comment by gwagnerGH** [comment]
We've now made several code fixes that should take care of what appears to be a cross-platform issue. Please try to re-run the latest (from here, Github). It's not yet been pushed to pip. Your IndexError should be resolved now. Please let me know if not.
